config/routes.rb
Mynotes::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "connect" => "sessions#connect", :as => "connect"

  resources :users
  resources :sessions
  resources :user_notes

  root 'user_notes#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :uname
  validates_uniqueness_of :uname

  has_many :user_notes

  def self.authenticate(uname, password)
    user = find_by_uname(uname)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/user_note.rb
class UserNote < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  helper_method :current_user

  private

  def authenticate_user!
    redirect_to log_in_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate_user!

  def new
  end

  def create
    user = User.authenticate(params[:uname], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/user_notes_controller.rb
class UserNotesController < ApplicationController

  before_filter :set_user_note, except: [:index, :new, :create]

  def index
    @user_notes = current_user.user_notes
  end

  def create
    service = UserNotesService.new(current_user)
    @user_note = service.create_note_from(params[:new_note])
    @user_notes = service.all_notes
    respond_to do |format|
      format.html { redirect_to(user_notes_url) }
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html { redirect_to(user_notes_url) }
      format.js
    end
  end

  def update
    @user_note.update_attribute('notes', params[:text]) if @user_note.notes != params[:text]

    respond_to do |format|
      format.html { redirect_to(edit_user_note_path(@user_note)) }
      format.js
    end
  end

  def destroy
    @user_notes = current_user.user_notes
    @user_note.destroy
    respond_to do |format|
      format.html { redirect_to(user_notes_url) }
      format.js
    end
  end


  private

  def set_user_note
    #@user_note = current_user.user_notes.first || current_user.user_notes.new
    @user_note = UserNote.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!

  def new
    @user = User.new
  end

  def create
    p user_params
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:uname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block)}
    uri = URI.parse(CONFIG[:faye][:host_url])
    Net::HTTP.post_form(uri, :message => message.to_json)
  rescue => e
    Rails.logger.error ">>>>> Could not broadcast message! Is faye server down or not connected?"
  end
end

app/helpers/user_notes_helper.rb
module UserNotesHelper
  def format_friendly_time(date_time)
    now = Time.now
    today = now.beginning_of_day..now.end_of_day
    yesterday = (now - 1.day).beginning_of_day..(now - 1.day).end_of_day
    if today.cover?(date_time)
      format = "Today "
    elsif yesterday.cover?(date_time)
      format = "Yesterday "
    else
      format = Time.now.year - date_time.year > 0 ? "%b %d %Y " : "%b %d "
    end
    date_time.strftime(format += "at %I:%M%p")
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mynotes
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "application", "#{CONFIG[:faye][:host_url]}.js"
    = csrf_meta_tags
  %body
    %p.notice
      %em.inner= flash.notice
    = yield

app/views/user_notes/_user_notes.html.haml
- user_notes.each do |note|
  = form_tag user_note_path(note), method: :put, remote: true do
    .note[note]
      .left= note.notes
      .right
        .timestamp
          %small=format_friendly_time(note.created_at)
        %span(class = 'edit_delete')
          -#= link_to 'Edit', edit_user_note_path(note), method: :get, remote: :true
          -#&nbsp;
          = link_to 'Delete', user_note_path(note), method: :delete, remote: :true
        %span(class = 'save_cancel hidden')
          = submit_tag 'Update', name: 'update_note'
    -#.clear[note]
  -#.clear[note]

app/views/user_notes/create.js.haml
:plain
  $('#notes').html("#{escape_javascript(render('user_notes', user_notes: @user_notes))}");
  $('#add_note textarea').val('');
  $('#add_note input[type="submit"]').attr('disabled', 'disabled');
  $('#notes .note:even').css("backgroundColor", "#E9E9E9");

- broadcast("/user_notes/update") do
  $('#notes').html("#{escape_javascript(render('user_notes', user_notes: @user_notes))}");

app/views/user_notes/destroy.js.haml
var selector = $('#notes .user_note#user_note_#{@user_note.id}');
selector.fadeOut();
selector.remove();
$('#notes .note:even').css("backgroundColor", "#E9E9E9");

- broadcast("/user_notes/update") do
  $('#notes').html("#{escape_javascript(render('user_notes', user_notes: @user_notes))}");

app/views/user_notes/edit.html.haml
%h2.em= "Notes for #{current_user.uname}:"
.flash_notice
= form_for @user_note, method: 'PUT', remote: true do |f|
  = f.text_area :notes, id: "notes_text_area_#{@user_note.id}", class: 'note_size'
  %br
  = f.submit :save, id: 'save_button'

app/views/user_notes/edit.js.haml
var selector = $('#notes .user_note#user_note_#{@user_note.id} .left');
var content = selector.html();
var rows = selector.height()/17;
var textarea = $('<textarea />').attr('name', 'text').attr('rows', rows).addClass('left').css('font-size', '.8em').html(content);
selector.html(textarea);
$('#notes .user_note#user_note_#{@user_note.id} .right .control .edit_delete').toggleClass('hidden', true);
$('#notes .user_note#user_note_#{@user_note.id} .right .control .save_cancel').toggleClass('hidden', false);

app/views/user_notes/index.html.haml
#notes_panel
  %strong Notes:
  #notes
    = render partial: 'user_notes', locals: {user_notes: @user_notes}
  %br
  #add_note
    = form_tag user_notes_path, remote: true do
      = text_area_tag 'new_note', '', class: 'add_note_text'
      = submit_tag 'Add Note', name: 'add_note', disabled: :disabled

app/views/user_notes/update.js.haml
$('#notes .user_note#user_note_#{@user_note.id} .left').remove("textarea");
$('#notes .user_note#user_note_#{@user_note.id} .left').html('#{@user_note.notes}');
$('#notes .user_note#user_note_#{@user_note.id} .right .control .edit_delete').toggleClass('hidden', false);
$('#notes .user_note#user_note_#{@user_note.id} .right .control .save_cancel').toggleClass('hidden', true);

- broadcast("/user_notes/update") do
  $("#notes_text_area_#{@user_note.id}").val("#{@user_note.notes}");

app/views/users/new.html.haml
%h1 Sign Up

= form_for @user do |f|
  - if @user.errors.present?
    %div.error_messages
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  %p
    %label User name
    %br
    = f.text_field :uname
  %p
    %label Password
    %br
    = f.password_field :password
  %p
    %label Confirm password
    %br
    = f.password_field :password_confirmation

  %p.button
    = f.submit